name: Test Plugin
main: com.redstonefreak589.info.RankDisplay
version: 1.0
description: >
             Rank Displayer for SlimCity server. Custom made by Redstonefreak589
commands:
  rank:
    description: Tells the player what each rank does. Used for the ranks system on slimcraftcity.weebly.com